"use strict";
exports.__esModule = true;
var userController_1 = require("./../controllers/userController");
var express_1 = require("express");
var userController_2 = require("../controllers/userController");
var authMiddleware_1 = require("../middleware/authMiddleware");
var router = express_1["default"].Router();
router.get('/', authMiddleware_1["default"], userController_2.getUsers);
router.post('/validate', authMiddleware_1["default"], userController_1.validateUser);
router.put('/:id', authMiddleware_1["default"], userController_1.updateUser);
router["delete"]('/:id', authMiddleware_1["default"], userController_2.deleteUser);
router.post('/signup', userController_2.register);
router.post('/signin', userController_2.login);
router.post('/signout', userController_1.logout);
exports["default"] = router;
