export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL';

export const NOTIFICATION_READ_REQUEST = 'NOTIFICATION_READ_REQUEST';
export const NOTIFICATION_READ_SUCCESS = 'NOTIFICATION_READ_SUCCESS';
export const NOTIFICATION_READ_FAIL = 'NOTIFICATION_READ_FAIL';

export const NOTIFICATION_READ_ALL_REQUEST = 'NOTIFICATION_READ_ALL_REQUEST';
export const NOTIFICATION_READ_ALL_SUCCESS = 'NOTIFICATION_READ_ALL_SUCCESS';
export const NOTIFICATION_READ_ALL_FAIL = 'NOTIFICATION_READ_ALL_FAIL';

export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST';
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS';
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL';
