export const TICKET_LIST_REQUEST = 'TICKET_LIST_REQUEST';
export const TICKET_LIST_SUCCESS = 'TICKET_LIST_SUCCESS';
export const TICKET_LIST_FAIL = 'TICKET_LIST_FAIL';

export const TICKET_DETAILS_REQUEST = 'TICKET_DETAILS_REQUEST';
export const TICKET_DETAILS_SUCCESS = 'TICKET_DETAILS_SUCCESS';
export const TICKET_DETAILS_FAIL = 'TICKET_DETAILS_FAIL';

export const TICKET_CREATE_REQUEST = 'TICKET_CREATE_REQUEST';
export const TICKET_CREATE_SUCCESS = 'TICKET_CREATE_SUCCESS';
export const TICKET_CREATE_FAIL = 'TICKET_CREATE_FAIL';
